### pokemon
GET https://pokeapi.co/api/v2/pokemon/ditto

### Auth
GET http://localhost:3000/api/auth/all

### register
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "user_id": "0ccd38fa-0ea5-4cd4-a876-77b9d6841106",
    "user_name": "Sebastian tres",
    "nick_name": "happy man 17",
    "password": "12345678",
    "email": "email-quince@gmail.com",
    "profile_image": ""
}

### login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "email-trece@gmail.com",
    "password": "12345678"
}

# insert INTO public.users (user_id, user_name, nick_name, password, email, profile_image) values ('0ccd39fa-0ea5-4cd4-a876-77b9d6841106', 'Sebastian', 'happy', '12345', 'email@gmail.com', '');
