### pokemon
GET https://pokeapi.co/api/v2/pokemon/ditto

# User ------------------------------

### Auth
GET http://localhost:3000/api/auth/all

### User By id
GET http://localhost:3000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmNjNkNmVhLTNhNWMtNDUzMC1iZmI1LWYzN2ViMDliYzdjNyIsImlhdCI6MTY5ODU5MTc5NywiZXhwIjoxNjk4NTk4OTk3fQ.hblV54rktcxsFSToJlx4jeJYDyVWUHdwtpuiZRfn7m8

### register
POST http://localhost:3000/api/auth/register
content-type: application/json

{
  "user_id": "0ccd38fa-0ea5-4cd4-a876-77b9d6841106",
  "user_name": "Sebastian",
  "nick_name": "happyMan 17",
  "password": "12345678",
  "email": "email-uno@gmail.com",
  "profile_image": ""
}

### login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "email": "email-quince@gmail.com",
  "password": "12345678"
}

### Update
PUT http://localhost:3000/api/user/update
content-type: application/json

{
  "user_id": "dd654a34-b34c-4429-8ab5-f1ca401758d8",
  "user_name": "testUserName",
  "nick_name": "testNickName",
  "profile_image": ""
}

# Event -------------------------
### All
GET http://localhost:3000/api/event/all

### By id
GET http://localhost:3000/api/event/323c344c-6a3a-4e1b-af51-3228c946d893

### Create event
POST http://localhost:3000/api/event/create
content-type: application/json

{
  "event_id": "0ccd38fa-0ea5-4cd4-a876-77b9d6841106",
  "user_id": "1f9f2236-bd07-4940-bc6f-367273b1d317",
  "event_name": "Cumple Gaby",
  "description": "Vamos a ir a acampar",
  "type": "Celebracion",
  "logo": "",
  "has_activity": false
}

### Update event
PUT  http://localhost:3000/api/event/update
content-type: application/json

{
  "event_id": "323c344c-6a3a-4e1b-af51-3228c946d893",
  "event_name": "Cumple Gaby",
  "description": "Vamos a ir a acampar",
  "type": "Celebracion",
  "has_activity": false,
  "has_been_done": true
}

# Activities -------------------------
### All
GET http://localhost:3000/api/activity/all

### by id
GET http://localhost:3000/api/activity/323c344c-6a3a-4e1b-af51-3228c946d893

### Create activity
POST  http://localhost:3000/api/activity/create
content-type: application/json

{
  "event_id": "323c344c-6a3a-4e1b-af51-3228c946d893",
  "description": "Vamos a hacer una fiesta",
  "total_activity_value": 50000,
  "is_by_percentage": true
}

### Update activity
PUT  http://localhost:3000/api/activity/update
content-type: application/json

{
  "activity_id": "150055d3-997d-4d53-97be-5e5eba840e7f",
  "description": "Vamos a hacer una fiesta",
  "total_activity_value": 50000,
  "is_by_percentage": true,
  "has_been_done": true
}


### Avtivity By event id
GET http://localhost:3000/api/activity

# Contacts -------------------------
### All
GET http://localhost:3000/api/contact/all

### add contact
POST http://localhost:3000/api/contact/create
content-type: application/json

{
  "user_id": "9f7acfbb-1148-41dc-a122-3d2a7c42be7c",
  "friend_id": "be46e178-93ff-48ed-8096-4dfa431cf422"
}

# insert INTO public.users (user_id, user_name, nick_name, password, email, profile_image) values ('0ccd39fa-0ea5-4cd4-a876-77b9d6841106', 'Sebastian', 'happy', '12345', 'email@gmail.com', '');
